DELETE http://localhost:3003/api/relationships/631c8f6301f5f3b7c27956ce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzFjOGY2MzAxZjVmM2I3YzI3OTU2ZDAiLCJpYXQiOjE2NjI4Nzc3MzAsImV4cCI6MTY2Mjg4MTMzMH0.fPA3jbWluqqnAb8uHOshieoYgpDOLilL2a7VXCIiG6Y

{
    "userId":"631c90e401f5f3b7c27956db"
}